
// state:
// -checklists:
//     -byId
//     -order
//     -isFetching
//     -error

export const FETCH_CHECKLISTS_STARTED = 'FETCH_CHECKLISTS_STARTED';
export const FETCH_CHECKLISTS_COMPLETED = 'FETCH_CHECKLISTS_COMPLETED';
export const FETCH_CHECKLISTS_FAILED = 'FETCH_CHECKLISTS_FAILED';

export const ADD_CHECKLIST_STARTED = 'ADD_CHECKLIST_STARTED';
export const ADD_CHECKLIST_COMPLETED = 'ADD_CHECKLIST_COMPLETED';
export const ADD_CHECKLIST_FAILED = 'ADD_CHECKLIST_FAILED';

export const REMOVE_CHECKLIST_STARTED = 'REMOVE_CHECKLIST_STARTED';
export const REMOVE_CHECKLIST_COMPLETED = 'REMOVE_CHECKLIST_COMPLETED';
export const REMOVE_CHECKLIST_FAILED = 'REMOVE_CHECKLIST_FAILED';
