
// state:
// -elements:
//     -byId
//     -order
//     -isFetching
//     -error

export const FETCH_CHECKELEMENTS_STARTED = 'FETCH_CHECKELEMENTS_STARTED';
export const FETCH_CHECKELEMENTS_COMPLETED = 'FETCH_CHECKELEMENTS_COMPLETED';
export const FETCH_CHECKELEMENTS_FAILED = 'FETCH_CHECKELEMENTS_FAILED';

export const ADD_CHECKELEMENT_STARTED = 'ADD_CHECKELEMENT_STARTED';
export const ADD_CHECKELEMENT_COMPLETED = 'ADD_CHECKELEMENT_COMPLETED';
export const ADD_CHECKELEMENT_FAILED = 'ADD_CHECKELEMENT_FAILED';

export const REMOVE_CHECKELEMENT_STARTED = 'REMOVE_CHECKELEMENT_STARTED';
export const REMOVE_CHECKELEMENT_COMPLETED = 'REMOVE_CHECKELEMENT_COMPLETED';
export const REMOVE_CHECKELEMENT_FAILED = 'REMOVE_CHECKELEMENT_FAILED';
