
// state:
// -lists:
//     -byId
//     -order
//     -isFetching
//     -error

export const FETCH_NOTIFICATIONS_STARTED = 'FETCH_NOTIFICATIONS_STARTED';
export const FETCH_NOTIFICATIONS_COMPLETED = 'FETCH_NOTIFICATIONS_COMPLETED';
export const FETCH_NOTIFICATIONS_FAILED = 'FETCH_NOTIFICATIONS_FAILED';

export const REMOVE_NOTIFICATION_STARTED = 'REMOVE_NOTIFICATION_STARTED';
export const REMOVE_NOTIFICATION_COMPLETED = 'REMOVE_NOTIFICATION_COMPLETED';
export const REMOVE_NOTIFICATION_FAILED = 'REMOVE_NOTIFICATION_FAILED';
